### ISSUE TITLE
UnboundLocalError: local variable 'hooked_open' referenced before assignment

### ISSUE THREAD

**Issue by a2505** [kaqijiang/Auto-GPT-ZH#15]
Auto-GPT 正在启动...
Traceback (most recent call last):
  File "D:\Software\anaconda3\envs\gpt\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Software\anaconda3\envs\gpt\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Project\Auto-GPT-ZH\autogpt\__main__.py", line 7, in <module>
    autogpt.localization.hook_open()
  File "E:\Project\Auto-GPT-ZH\autogpt\localization.py", line 148, in hook_open
    if not hooked_open:
UnboundLocalError: local variable 'hooked_open' referenced before assignment

**Comment by yanzhao77** [comment]
同样的问题

**Comment by ghost** [comment]
#16 对不起对不起（

**Comment by ghost** [comment]
昨晚搞的 dirty 提交
早上起来没机器但是重新清理一下代码
结果把它忘了（
