### ISSUE TITLE
运行python -m autogpt直接报错

### ISSUE THREAD

**Issue by ayingk** [kaqijiang/Auto-GPT-ZH#4]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

Traceback (most recent call last):
  File "D:\java\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\java\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\java\Auto-GPT-ZH-main\autogpt\__main__.py", line 4, in <module>
    from autogpt.agent.agent import Agent
  File "D:\java\Auto-GPT-ZH-main\autogpt\agent\__init__.py", line 1, in <module>
    from autogpt.agent.agent import Agent
  File "D:\java\Auto-GPT-ZH-main\autogpt\agent\agent.py", line 2, in <module>
    from autogpt.app import execute_command, get_command
  File "D:\java\Auto-GPT-ZH-main\autogpt\app.py", line 12, in <module>
    from autogpt.commands.web_requests import scrape_links, scrape_text
  File "D:\java\Auto-GPT-ZH-main\autogpt\commands\web_requests.py", line 12, in <module>
    from autogpt.memory import get_memory
  File "D:\java\Auto-GPT-ZH-main\autogpt\memory\__init__.py", line 9, in <module>
    from autogpt.memory.redismem import RedisMemory
  File "D:\java\Auto-GPT-ZH-main\autogpt\memory\redismem.py", line 9, in <module>
    from redis.commands.search.field import TextField, VectorField
  File "D:\java\python3\lib\site-packages\redis\commands\search\__init__.py", line 3, in <module>
    from ...asyncio.client import Pipeline as AsyncioPipeline
  File "D:\java\python3\lib\site-packages\redis\asyncio\__init__.py", line 1, in <module>
    from redis.asyncio.client import Redis, StrictRedis
  File "D:\java\python3\lib\site-packages\redis\asyncio\client.py", line 646, in <module>
    class PubSub:
  File "D:\java\python3\lib\site-packages\redis\asyncio\client.py", line 713, in PubSub
    def close(self) -> Awaitable[NoReturn]:
  File "D:\java\python3\lib\typing.py", line 251, in inner
    return func(*args, **kwds)
  File "D:\java\python3\lib\typing.py", line 626, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "D:\java\python3\lib\typing.py", line 626, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "D:\java\python3\lib\typing.py", line 135, in _type_check
    raise TypeError(f"Plain {arg} is not valid as type argument")
TypeError: Plain typing.NoReturn is not valid as type argument

### Expected behavior 🤔

无法正常运行

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by kaqijiang** [comment]
更新版本
